{% set name = "carto" %}
{% set version = "1.11.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62803241c902852598b5c899f677a672048481e8fade71bd0146fb1af68b61e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - carto

about:
  home: https://github.com/CartoDB/carto-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SDK around CARTO's APIs
  dev_url: https://github.com/CartoDB/carto-python

extra:
  recipe-maintainers:
    - Jesus89
